# Generated by Django 5.2.5 on 2026-07-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_book_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], default='borrowed', max_length=10),
        ),
    ]
